<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.4" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.1" />
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="8.1.1" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.9.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\assets\attachments\" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\pages\attachments\attachment-create.html" />
      <_ContentIncludedByDefault Remove="wwwroot\pages\attachments\attachment-details.html" />
      <_ContentIncludedByDefault Remove="wwwroot\pages\attachments\attachment-edit.html" />
      <_ContentIncludedByDefault Remove="wwwroot\pages\attachments\attachments.html" />
      <_ContentIncludedByDefault Remove="wwwroot\css\styles.css" />
      <_ContentIncludedByDefault Remove="wwwroot\attachments\css\attachments.css" />
      <_ContentIncludedByDefault Remove="wwwroot\attachments\js\attachments.js" />
      <_ContentIncludedByDefault Remove="wwwroot\attachments\pages\attachment-create.html" />
      <_ContentIncludedByDefault Remove="wwwroot\attachments\pages\attachment-details.html" />
      <_ContentIncludedByDefault Remove="wwwroot\attachments\pages\attachment-edit.html" />
      <_ContentIncludedByDefault Remove="wwwroot\attachments\pages\attachments.html" />
      <_ContentIncludedByDefault Remove="wwwroot\categories\categorie-create.html" />
      <_ContentIncludedByDefault Remove="wwwroot\categories\categorie-details.html" />
      <_ContentIncludedByDefault Remove="wwwroot\categories\categorie-edit.html" />
      <_ContentIncludedByDefault Remove="wwwroot\categories\categories.css" />
      <_ContentIncludedByDefault Remove="wwwroot\categories\categories.html" />
      <_ContentIncludedByDefault Remove="wwwroot\categories\categories.js" />
      <_ContentIncludedByDefault Remove="wwwroot\statuses\status-create.html" />
      <_ContentIncludedByDefault Remove="wwwroot\statuses\status-details.html" />
      <_ContentIncludedByDefault Remove="wwwroot\statuses\status-edit.html" />
      <_ContentIncludedByDefault Remove="wwwroot\statuses\statuses.css" />
      <_ContentIncludedByDefault Remove="wwwroot\statuses\statuses.html" />
      <_ContentIncludedByDefault Remove="wwwroot\statuses\statuses.js" />
      <_ContentIncludedByDefault Remove="wwwroot\roles\role-create.html" />
      <_ContentIncludedByDefault Remove="wwwroot\roles\role-details.html" />
      <_ContentIncludedByDefault Remove="wwwroot\roles\role-edit.html" />
      <_ContentIncludedByDefault Remove="wwwroot\roles\roles.css" />
      <_ContentIncludedByDefault Remove="wwwroot\roles\roles.html" />
      <_ContentIncludedByDefault Remove="wwwroot\roles\roles.js" />
    </ItemGroup>

</Project>
